# (PART) PREPROCESSING TOOLS {-}

# Required Processing Tools {#preprocessing-tools}

There several tools out there that can help in preprocessing raw read. Listed below are some of most common tools used in understanding the characteristics of the read and their quality scores. Click on the hyperlinked tool to learn more how to install it.

- [Seqkit](https://bioinf.shenwei.me/seqkit/download/) [@seqkit2016]
- [FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/) [@fastqc2018]
- [MultiQC](https://multiqc.info/) [@multiqc2016]
- [BBMap](https://sourceforge.net/projects/bbmap/files/latest/download) platform [@bbmap2016] 
- [Kneaddata](https://huttenhower.sph.harvard.edu/kneaddata/) in biobakery platform [@kneaddata2022] 
 

# Installing Preprocessing Tools on Mac {#install-on-mac}

## Installing seqkit
```bash
wget --no-check-certificate https://github.com/shenwei356/seqkit/releases/download/v0.8.0/seqkit_darwin_amd64.tar.gz
tar -zxvf seqkit_darwin_amd64.tar.gz
mv seqkit code/
cp code/seqkit ~/bin/
rm seqkit_darwin_amd64.tar.gz
```

## Installing fastqc
```bash
wget --no-check-certificate https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.7.zip
unzip fastqc_v0.11.7.zip
chmod 755 FastQC/fastqc
mv -v FastQC code/
cp code/FastQC/fastqc ~/bin/
rm fastqc_v0.11.7.zip
```

## Installing bbmap
```bash
wget --no-check-certificate https://sourceforge.net/projects/bbmap/files/BBMap_37.90.tar.gz
tar -xvzf BBMap_37.90.tar.gz
mv -v bbmap code/
cp code/bbmap/bbduk.sh ~/bin/
rm BBMap_37.90.tar.gz
```


# Installing Preprocessing Tools on Linux {#install-on-linux}

## Install seqkit
```bash
wget --no-check-certificate https://github.com/shenwei356/seqkit/releases/download/v0.8.0/seqkit_darwin_amd64.tar.gz
tar -zxvf seqkit_darwin_amd64.tar.gz
mv seqkit code/
cp code/seqkit ~/bin/
rm seqkit_darwin_amd64.tar.gz
```

## Install fastqc
```bash
wget --no-check-certificate https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.7.zip
unzip fastqc_v0.11.7.zip
chmod 755 FastQC/fastqc
mv -v FastQC code/
cp code/FastQC/fastqc ~/bin/
rm fastqc_v0.11.7.zip
```

## Install bbmap
```bash
wget --no-check-certificate https://sourceforge.net/projects/bbmap/files/BBMap_37.90.tar.gz
tar -xvzf BBMap_37.90.tar.gz
mv -v bbmap code/
cp code/bbmap/bbduk.sh ~/bin/
rm BBMap_37.90.tar.gz
```


# Installing Preprocessing Tools on Windows {#install-on-win}

## Install seqkit
```bash
wget --no-check-certificate https://github.com/shenwei356/seqkit/releases/download/v0.8.0/seqkit_darwin_amd64.tar.gz
tar -zxvf seqkit_darwin_amd64.tar.gz
mv seqkit code/
cp code/seqkit ~/bin/
rm seqkit_darwin_amd64.tar.gz
```

## Install fastqc
```bash
wget --no-check-certificate https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.7.zip
unzip fastqc_v0.11.7.zip
chmod 755 FastQC/fastqc
mv -v FastQC code/
cp code/FastQC/fastqc ~/bin/
rm fastqc_v0.11.7.zip
```

## Install bbmap
```bash
wget --no-check-certificate https://sourceforge.net/projects/bbmap/files/BBMap_37.90.tar.gz
tar -xvzf BBMap_37.90.tar.gz
mv -v bbmap code/
cp code/bbmap/bbduk.sh ~/bin/
rm BBMap_37.90.tar.gz
```

> Note that the links for each tool may be outdated. Make sure to check for latest instructions online.





